
spring.application.name=quarto-inteligente-api
spring.datasource.url=jdbc:postgresql://localhost:5432/quarto_inteligente
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.api-key=${API_KEY:troque-por-uma-chave-secreta}

mqtt.broker-url=${MQTT_BROKER_URL:tcp://10.161.41.138:1883}
mqtt.topic=casa/quarto/sensor/temperatura-umidade
mqtt.client-id=spring-boot-api
mqtt.username=${MQTT_USERNAME:springboot}
mqtt.password=${MQTT_PASSWORD:0210}